services:
  volumemount-env-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SQLSERVER_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - type: "volume"
        target: "/var/opt/mssql"
        source: "volumemount-sqlserver-data"
        read_only: false
    networks:
      - "aspire"
  blazorweb:
    image: "${BLAZORWEB_IMAGE}"
    command:
      - "/bin/sh"
      - "-c"
      - "chown -R app:app /app/wwwroot/uploads && chmod -R 755 /app/wwwroot/uploads && exec su app -c 'dotnet /app/VolumeMount.BlazorWeb.dll'"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${BLAZORWEB_PORT}"
      ConnectionStrings__sqldb: "Server=sqlserver,1433;User ID=sa;Password=${SQLSERVER_PASSWORD};TrustServerCertificate=true;Initial Catalog=sqldb"
      SQLDB_HOST: "sqlserver"
      SQLDB_PORT: "1433"
      SQLDB_USERNAME: "sa"
      SQLDB_PASSWORD: "${SQLSERVER_PASSWORD}"
      SQLDB_URI: "mssql://sa:${SQLSERVER_PASSWORD}@sqlserver:1433/sqldb"
      SQLDB_JDBCCONNECTIONSTRING: "jdbc:sqlserver://sqlserver:1433;trustServerCertificate=true;databaseName=sqldb"
      SQLDB_DATABASENAME: "sqldb"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://volumemount-env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "blazorweb"
    ports:
      - "${BLAZORWEB_PORT}"
    volumes:
      - type: "volume"
        target: "/app/wwwroot/uploads"
        source: "volumemount-blazor-uploads"
        read_only: false
    depends_on:
      sqlserver:
        condition: "service_started"
    user: "root"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  volumemount-sqlserver-data:
    driver: "local"
  volumemount-blazor-uploads:
    driver: "local"
